---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.cache # includes bowers cache

before_script:
  - yarn global add bower # this would be better to do in install step,
  - bower install         #   once travis' yarn support improves

script:
  - yarn test
